services:
  - type: web
    name: multi-cancer-classifier
    env: python
    runtime: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DISABLE_POETRY
        value: "1"
      - key: POETRY_ACTIVE
        value: "0"
